web: php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT
worker: php artisan queue:work --tries=3 --sleep=3 --timeout=60
workerInstant: php artisan queue:work redis_instant --queue=instant --tries=1 --timeout=60 --sleep=0
