name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup app
        run: make setup CI=1

      - name: Run frontend checks
        run: make pnpm run test

      - name: Run tests
        run: make artisan test

      - name: Run parallel tests with coverage
        run: make composer test


  detect:
    name: Detect alive color
    runs-on: ubuntu-latest
#    needs: tests  # Wait for tests to pass
    outputs:
      alive: ${{ steps.set_alive.outputs.alive }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect alive backend
        id: detect_back
        run: |
          if curl -s --max-time 5 ${{ vars.BACK_BLUE_URL }}/api/health | grep -q '"status":"ok"'; then
            echo "alive=blue" >> $GITHUB_OUTPUT
          else
            echo "alive=green" >> $GITHUB_OUTPUT
          fi

      - name: Detect alive frontend
        id: detect_front
        run: |
          if curl -s --max-time 5 ${{ vars.FRONT_BLUE_URL }}/health | grep -q '"status":"ok"'; then
            echo "alive=blue" >> $GITHUB_OUTPUT
          else
            echo "alive=green" >> $GITHUB_OUTPUT
          fi
      

      - name: Set output
        id: set_alive
        run: |
          BACK="${{ steps.detect_back.outputs.alive }}"
          FRONT="${{ steps.detect_front.outputs.alive }}"
          
          if [[ "$BACK" != "$FRONT" ]]; then
            echo "❌ État incohérent : back=$BACK, front=$FRONT"
          exit 1
          fi
          
          echo "alive=$BACK" >> $GITHUB_OUTPUT

  deploy-back:
    name: Deploy backend to Scalingo
    runs-on: ubuntu-latest
    needs: detect
#    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node version
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Build MJML emails
        working-directory: backend
        run: |
          npm install -g mjml 
          npm run emails:build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH_KEY }}

      - name: Add Scalingo to known hosts
        run: ssh-keyscan -H ssh.osc-fr1.scalingo.com >> ~/.ssh/known_hosts

      - name: Push to Scalingo back-blue
        working-directory: ${{ github.workspace }}
        if: ${{ needs.detect.outputs.alive == 'green' }}
        run: |
          git config --global user.email "url@monitor.fr"
          git config --global user.name "URL MONITOR"
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:url-monitor-back-blue.git
          git fetch scalingo main || true
          git add -f backend/resources/views/mails/*.blade.php
          git commit --amend -m "chore: deploy $(date +%Y-%m-%d\ %H:%M)" --allow-empty
          git push scalingo HEAD:refs/heads/main --force

      - name: Push to Scalingo back-green
        working-directory: ${{ github.workspace }}
        if: ${{ needs.detect.outputs.alive == 'blue' }}
        run: |
          git config --global user.email "url@monitor.fr"
          git config --global user.name "URL MONITOR"
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:url-monitor-back-green.git
          git fetch scalingo main || true
          git add -f backend/resources/views/mails/*.blade.php
          git commit --amend -m "chore: deploy $(date +%Y-%m-%d\ %H:%M)" --allow-empty
          git push scalingo HEAD:refs/heads/main --force

  deploy-front:
    name: Deploy frontend to Scalingo
    runs-on: ubuntu-latest
    needs: detect
#    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH_KEY }}

      - name: Add Scalingo to known hosts
        run: ssh-keyscan -H ssh.osc-fr1.scalingo.com >> ~/.ssh/known_hosts

      - name: Push to Scalingo front-green
        working-directory: ${{ github.workspace }}
        if: ${{ needs.detect.outputs.alive == 'blue' }}
        run: |
          git config --global user.email "url@monitor.fr"
          git config --global user.name "URL MONITOR"
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:url-monitor-front-green.git
          git fetch scalingo main || true
          git commit --amend -m "chore: deploy $(date +%Y-%m-%d\ %H:%M)" --allow-empty
          git push scalingo HEAD:refs/heads/main --force

      - name: Push to Scalingo front-blue
        working-directory: ${{ github.workspace }}
        if: ${{ needs.detect.outputs.alive == 'green' }}
        run: |
          git config --global user.email "url@monitor.fr"
          git config --global user.name "URL MONITOR"
          git remote add scalingo git@ssh.osc-fr1.scalingo.com:url-monitor-front-blue.git
          git fetch scalingo main || true
          git commit --amend -m "chore: deploy $(date +%Y-%m-%d\ %H:%M)" --allow-empty
          git push scalingo HEAD:refs/heads/main --force
          

  update-reverse-proxy:
    name: Deploy reverse proxy to Scalingo
    runs-on: ubuntu-latest
    needs: [detect, deploy-back, deploy-front]
#    if: github.ref == 'refs/heads/main'

    steps:
      - name: Wait a minute ...
        run: sleep 60

      - name: Exchange token for Bearer Token
        id: exchange_token
        run: |
          TOKEN=$(curl -s -H "Accept: application/json" \
                       -H "Content-Type: application/json" \
                       -u ":${{ secrets.SCALINGO_API_TOKEN }}" \
                       -X POST https://auth.scalingo.com/v1/tokens/exchange \
                       | jq -r '.token')
          echo "bearer=$TOKEN" >> $GITHUB_OUTPUT

      - name: Update URL
        run: |
          ALIVE="${{ needs.detect.outputs.alive }}"
          TARGET=$([[ "$ALIVE" == "blue" ]] && echo "green" || echo "blue")
          
          jq -n --arg back "https://url-monitor-back-$TARGET.osc-fr1.scalingo.io" \
                --arg front "https://url-monitor-front-$TARGET.osc-fr1.scalingo.io" \
                '{variables:[{name:"BACKEND_URL",value:$back},{name:"FRONTEND_URL",value:$front}]}' \
            | curl -H "Accept: application/json" \
                   -H "Content-Type: application/json" \
                   -H "Authorization: Bearer ${{ steps.exchange_token.outputs.bearer }}" \
                   -X PUT https://api.osc-fr1.scalingo.com/v1/apps/url-monitor-reverse-proxy/variables \
                   -d @-

  scale-down-apps:
    name: Scale down to 0 apps previously alive
    runs-on: ubuntu-latest
    needs: [detect, update-reverse-proxy]
    #    if: github.ref == 'refs/heads/main'

    steps:
      - name: Wait a minute ...
        run: sleep 60

      - name: Exchange token for Bearer Token
        id: exchange_token
        run: |
          TOKEN=$(curl -s -H "Accept: application/json" \
                       -H "Content-Type: application/json" \
                       -u ":${{ secrets.SCALINGO_API_TOKEN }}" \
                       -X POST https://auth.scalingo.com/v1/tokens/exchange \
                       | jq -r '.token')
          echo "bearer=$TOKEN" >> $GITHUB_OUTPUT

      - name: Scale down old backend
        run: |
          ALIVE="${{ needs.detect.outputs.alive }}"
          
          curl -H "Accept: application/json" -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ steps.exchange_token.outputs.bearer }}" \
            -X POST "https://api.osc-fr1.scalingo.com/v1/apps/url-monitor-back-$ALIVE/scale" -d \
            '{
              "containers": [
                {
                  "name": "web",
                  "amount": 0
                },
                {
                  "name": "worker",
                  "amount": 0
                },
                {
                  "name": "workerInstant",
                  "amount": 0
                }
              ]
            }'

      - name: Scale down old frontend
        run: |
          ALIVE="${{ needs.detect.outputs.alive }}"
          
          curl -H "Accept: application/json" -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ steps.exchange_token.outputs.bearer }}" \
            -X POST "https://api.osc-fr1.scalingo.com/v1/apps/url-monitor-front-$ALIVE/scale" -d \
            '{
              "containers": [
                {
                  "name": "web",
                  "amount": 0
                }
              ]
            }'